# 异常处理

dart的异常处理跟其他语言类似，但也有自己的特性。

## 异常类型

Dart 中有两种主要的异常类型：

* Error：表示程序无法恢复的错误，如内存不足、编译时错误等。
* Exception：表示程序可以捕获并处理的异常情况。

## 抛异常

1. `throw` 关键字抛出异常

```dart
throw FormatException('Expected at least 1 section');

//也可以直接写错误信息
throw 'Out of llamas!';
```

## 捕获异常

结构：try..catch{}finally{}

* try 块：包含可能会抛出异常的代码。
* catch 块：当 try 块中的代码抛出异常时执行。
* finally 块：无论是否发生异常，都会执行的代码块。

```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
} on Exception catch (e) {
  print('Unknown exception: $e');
} catch (e) {
  print('Something really unknown: $e');
}finally{
    //同java 最终一定会走这里
}
```

### 重新捕获

如果 try 块中的代码抛出异常，并且 catch 块没有捕获到异常，或者 catch 块中的代码再次抛出异常，你可以使用 rethrow 关键字将异常传递给上层的异常处理器。

```dart
try {
  try {
    // 可能会抛出异常的代码
  } catch (e) {
    // 处理异常
    rethrow; // 将异常传递给上层的异常处理器
  }
} catch (e) {
  // 上层异常处理器
}
```

### `on` 捕获特定异常类型

```dart
try {
  // ...
} on SpecificExceptionType {
  // 处理 SpecificExceptionType 类型的异常
}

```

### try-catch表达式

这就是dart不一样的地方，可以作为表达式使用

```dart
var result = try {
  // 返回值的代码
} catch (e) {
  // 异常处理代码，可以返回一个替代值
  '替代值';
}
```

## 断言

Dart 中的 `assert` 关键字用于检查在调试期间应该为真的条件。如果条件为假，assert 会抛出 AssertionError。

```dart
assert(condition, '错误信息');
```
